### PR TITLE
Fix broken links in docs

### PR DESCRIPTION
**Pull request by colinodell**
## 💸 TL;DR
Updates links that pointed to non-public resources

## 📜 Details
After attending yesterday's (awesome) KubeCon session about this library, I started combing through the docs but kept hitting broken or private links.  I've therefore attempted to update those links in this PR to the best location I could determine.

Please double-check my changes here (especially in the `sdk-fsm-reconciler.md` file) since I haven't actually used this library yet and don't want to mislead other developers by pointing to the wrong places! 😅 

## 🧪 Testing Steps / Validation
I manually clicked the updated links to ensure they loaded?

## ✅ Checks

- [ ] CI tests (if present) are passing
- [x] Adheres to code style for repo
- [ ] Contributor License Agreement (CLA) completed if not a Reddit employee

### CODE REVIEW

**Review by harveyxia — APPROVED** [review]
(Karan's OOO this week so I'll take over the review) Just one minor tweak, otherwise LGTM. Thanks for these fixes!

**Comment by harveyxia** [comment]
I'm fixing CI for forked PRs here, https://github.com/reddit/achilles-sdk/pull/9 (Github Actions doesn't allow usage of repo secrets for CI running on forked PRs, but since all dependencies are open sourced now we can fully remove this configuration)

**Comment by colinodell** [comment]
Thanks for the review! I've applied the suggestions and updated against `main`.

**Review by harveyxia — APPROVED** [review]
Thanks again for this contribution

**Pull request merged**
